### PR TITLE
Adds stackblitz sample app

### PR DESCRIPTION
**Pull request by vinagreti**
I can give you ownership of the app. Just send me your email on stackblitz.

### CODE REVIEW

**Comment by Nillcon248** [comment]
Hello, I freaking glad you decided to contribute to this library, but this example doesn't show how the decorator really works. Have you seen [example](https://stackblitz.com/edit/angular-ivy-3xkfrv?file=src/app/unsubscribe-decorator/unsubscribe-decorator.component.ts) I added to the topic on medium? Try to open devTools, where you can see that streams are removed after the component has destroing.
image

**Comment by Nillcon248** [comment]
My mail: nillcon248@gmail.com
and I have telegram, if you want to discuss something, you can write me) - [nillcon248](https://t.me/Nillcon)

**Comment by vinagreti** [comment]
My idea was to check if the decorator worked for streams declared after class instantiation.
The idea is to destroy a component and emit a new value to see if the subscription was unsubscribed. And it works as expected.
I suggest you to create a PR to include this decorator on angular/core. I think it is very useful and should be available out of the box as async pipe is.

**Comment by Nillcon248** [comment]
Sounds great, but I am not sure that someone will check this PR) Maybe I must more popularize this approach for detect some issues and get support from the community)

**Comment by vinagreti** [comment]
The angular team will check the PR. I can assure you. You only need to label it properly (I think with proposal label).
It is a real good idea to have that capability out of the box as beginners tend not to use async pipe nor OnPush.
And feel free to ignore my PR and maybe add your demo url to the README.md so people that get here have a way to try it with their own cases.
Nice to meet you. Thanks for the lib. I'll use it for sure.

**Pull request merged**
